language: python
python:
- '2.7'
before_install:
- apt-get update -qq
- apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  distributions: "sdist bdist_wheel"
  password:
    secure: K4nUGpELCyhmEvqVh7Q74W+9tOYO/btsj9q2MdiUTbxIQHBeRTsN2UIsi4CJD8CoVwD95x/6Cfxqh86sHEOpU3sRYV7W5wKH4OJ1n5f/KRuKFqQ7VR6KVap9hWg1HvXkT/XIfprom5dYeHv+fvhF5hryk1V5fPF2pTdjP/pUS9E=
  on:
    tags: true
    repo: opennode/nodeconductor
